title: Webová aplikace pro sdílení asistentů pro aplikaci DevAssistant
authorGN: Miroslav
authorFN: Hrončok
authorWithDegrees: Miroslav Hrončok
supervisor: Mgr. Bohuslav Kabrda
keywordsCS: web, vývojář, katalog, API
keywordsEN: web, developer, index, API
department: Katedra softwarového inženýrství
placeForDeclarationOfAuthenticity: V~Praze
declarationOfAuthenticityOption: 4
