title: Webová aplikace pro sdílení asistentů pro aplikaci DevAssistant
authorGN: Miroslav
authorFN: Hrončok
authorWithDegrees: Miroslav Hrončok
supervisor: Mgr. Bohuslav Kabrda
keywordsCS: web, vývojář, katalog, formát, API, Python, Django, YAML
keywordsEN: web, developer, index, format, API, Python, Django, YAML
department: Katedra softwarového inženýrství
placeForDeclarationOfAuthenticity: V~Praze
declarationOfAuthenticityOption: 4
